name: WRSetup

on: [push, workflow_dispatch]

jobs:
  setup-rdp:
    runs-on: windows-latest
    steps:
      - name: Download ngrok
        run: Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"

      - name: Extract ngrok
        run: Expand-Archive -Path "ngrok.zip" -DestinationPath "."

      - name: Authenticate ngrok
        run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Set Local Admin Password
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@sswOrd!" -Force)

      - name: Start ngrok tunnel
        run: .\ngrok.exe tcp 3389 > ngrok.log
        continue-on-error: true

      - name: Display ngrok tunnel information
        run: cat ngrok.lo
